user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

livre:
    resource: "@LivreBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
