livre_homepage:
    path:     /
    defaults: { _controller: LivreBundle:Default:index }

livre_biblio:
    path: /biblio
    defaults: { _controller: LivreBundle:Default:biblio }

livre_propos:
    path: /apropos
    defaults: { _controller: LivreBundle:Default:propos }

livre_ajout:
    path: /ajout
    defaults: { _controller: LivreBundle:Default:ajout }

livre_mabiblio:
    path: /mabiblio
    defaults: { _controller: LivreBundle:Default:mabiblio }
    
livre_livre:
    path: /livre/{id}
    defaults: { _controller: LivreBundle:Default:livre }
    
livre_echange:
    path: /echange/{id}
    defaults: { _controller: LivreBundle:Default:echange }
    
livre_suppr:
    path: /livre/{id}
    defaults: { _controller: LivreBundle:suppr }
    
livre_demande:
    path: /demande/{id}
    defaults: { _controller: LivreBundle:Default:demande }
    
livre_accept:
    path: /fin/{id}
    defaults: { _controller: LivreBundle:Default:validation }
    methods: GET
    requirements:
        id: \d