<?php

namespace LivreBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function joinImage(QueryBuilder $qb) {
        $qb
          ->leftJoin('l.imageLivre', 'i')
          ->addSelect('i')
        ;
    }

    public function findAllCustom() {
      $qb = $this->createQueryBuilder('l');
      // Jointure sur l'image
      $this->joinImage($qb);

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }

}
