<?php

namespace LivreBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function joinImage(QueryBuilder $qb) {
        $qb
          ->leftJoin('l.imageLivre', 'i')
          ->addSelect('i')
        ;
    }
    
    public function findAllCustom() {
      $qb = $this->createQueryBuilder('l');
      // Jointure sur l'image
      $this->joinImage($qb);

      return $qb
        ->getQuery()
        ->getResult()
      ;
    }
    
    public function findByTitleLike($title){
                $qb = $this->createQueryBuilder('l');
                $qb->where('l.title LIKE :user')
                ->setParameter('title', $title)
                ->orderBy('l.date_ajout', 'DESC');
    }
    
    public function findByUser($user){
        $qb = $this->createQueryBuilder('l');
        $qb->where('l.user = :user')
                ->setParameter('user', $user)
                ->orderBy('l.date_ajout', 'DESC')
        ;
        
        return $qb
                ->getQuery()
                ->getResult()
        ;
    }
    
}
